---
apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
stringData:
  conjur-map: |-   
    dbaddr: test/host1/host
    dbuser: test/host1/user
    dbpass: test/host1/pass
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-springboot
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-springboot
  labels:
    app: cityapp-springboot
spec:
  ports:
  - port: 8080
    nodePort: 30088
    name: http
  selector:
    app: cityapp-springboot
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cityapp-springboot
  name: cityapp-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cityapp-springboot
  template:
    metadata:
      labels:
        app: cityapp-springboot
      annotations:
        conjur.org/container-mode: sidecar
        conjur.org/secrets-refresh-interval: 30s
    spec:
      serviceAccountName: cityapp-springboot
      hostAliases:
      - ip: "{LAB_IP}"
        hostnames:
        - "mysql.{LAB_DOMAIN}"      
      containers:
      - name: cityapp
        image: huydd79/cityapp-springboot:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: conjur-access-token
            mountPath: /conjur
            readOnly: true
          - name: secret-volume
            mountPath: /etc/secret-volume
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: "db-creds"
              key: dbaddr
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: 'db-creds'
              key: dbuser
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: 'db-creds'
              key: dbpass
        - name: DB_PORT
          value: '3306'
        - name: DB_NAME
          value: world
      - name: conjurtok8ssecret
        image: docker.io/cyberark/secrets-provider-for-k8s:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: jwt-token
          mountPath: /var/run/secrets/tokens
        - mountPath: /run/conjur
          name: conjur-access-token
        - mountPath: /etc/conjur/ssl
          name: conjur-certs
        - mountPath: /conjur/podinfo
          name: podinfo
        env:
        - name: JWT_TOKEN_PATH
          value: /var/run/secrets/tokens/jwt
        - name: CONTAINER_MODE
          value: init
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_SECRETS
          value: db-creds
        - name: SECRETS_DESTINATION
          value: k8s_secrets
        envFrom:
          - configMapRef:
              name: apps-cm
      volumes:
        - name: secret-volume
          secret:
            secretName: db-creds
        - name: podinfo
          downwardAPI:
            items:
              - path: annotations
                fieldRef:
                  fieldPath: metadata.annotations
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: conjur-certs
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: cybrdemo
