---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-access
  namespace: cityapp
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: cityapp
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: cityapp
    name: cityapp-conjurtok8ssecret
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: secrets-access