apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: conjur
spec:
  refreshInterval: 55s
  secretStoreRef:
    # This name must match the metadata.name in the SecretStore
    name: conjur
    kind: SecretStore
  target:
    name: conjur-secret
  data:
  - secretKey: host
    remoteRef:
      key: test/host2/host
  - secretKey: user
    remoteRef:
      key: test/host2/user
  - secretKey: pass
    remoteRef:
      key: test/host2/pass
