---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-eso
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: conjur
spec:
  provider:
    conjur:
      url: {CONJUR_URL}
      caProvider:
        type: ConfigMap
        name: conjur-cm
        key: CONJUR_SSL_CERTIFICATE
      auth:
        jwt:
          account: {CONJUR_ACCOUNT}
          # The authn-jwt service ID
          serviceID: k8s
          # Service account to retrieve JWT token for
          serviceAccountRef:
            name: k8s-eso
            # [OPTIONAL] audiences to include in JWT token
            audiences:
              - cybrdemo
